In [1]:
import pandas as pd
df = pd.read_parquet('04_clean/level_01.parquet')
df.head()

,hhid,common_id,survey_name,year,fsu_serial_no,sector,state,nss_region,district,stratum,...,fod_subregion,sample_su_num,sample_subdiv_num,sec_stage_stratum_num,sample_hhld_num,questionnaire_num,level,svy_code,subcode_reason,multiplier
0,46667201,HCES2024466671010120613012 201103 201,HCES,2024,46667,1,1,12,6,13,...,110,3,NaN,2,1,H,1,1,NaN,16669
1,46667301,HCES2024466671010120613012 201103 301,HCES,2024,46667,1,1,12,6,13,...,110,3,NaN,3,1,H,1,1,NaN,24840
2,46667302,HCES2024466671010120613012 201103 302,HCES,2024,46667,1,1,12,6,13,...,110,3,NaN,3,2,H,1,1,NaN,24840
3,46667303,HCES2024466671010120613012 201103 303,HCES,2024,46667,1,1,12,6,13,...,110,3,NaN,3,3,H,1,1,NaN,24840
4,46667304,HCES2024466671010120613012 201103 304,HCES,2024,46667,1,1,12,6,13,...,110,3,NaN,3,4,H,1,1,NaN,24840

In [2]:
df.set_index('hhid', verify_integrity=True, inplace=True)
df.head()

,common_id,survey_name,year,fsu_serial_no,sector,state,nss_region,district,stratum,sub_stratum,...,fod_subregion,sample_su_num,sample_subdiv_num,sec_stage_stratum_num,sample_hhld_num,questionnaire_num,level,svy_code,subcode_reason,multiplier
hhid,,,,,,,,,,,,,,,,,,,,,
46667201,HCES2024466671010120613012 201103 201,HCES,2024,46667,1,1,12,6,13,1,...,110,3,NaN,2,1,H,1,1,NaN,16669
46667301,HCES2024466671010120613012 201103 301,HCES,2024,46667,1,1,12,6,13,1,...,110,3,NaN,3,1,H,1,1,NaN,24840
46667302,HCES2024466671010120613012 201103 302,HCES,2024,46667,1,1,12,6,13,1,...,110,3,NaN,3,2,H,1,1,NaN,24840
46667303,HCES2024466671010120613012 201103 303,HCES,2024,46667,1,1,12,6,13,1,...,110,3,NaN,3,3,H,1,1,NaN,24840
46667304,HCES2024466671010120613012 201103 304,HCES,2024,46667,1,1,12,6,13,1,...,110,3,NaN,3,4,H,1,1,NaN,24840

In [26]:
df[df.columns[5:]]

,state,nss_region,district,stratum,sub_stratum,panel,subsample,fod_subregion,sample_su_num,sample_subdiv_num,sec_stage_stratum_num,sample_hhld_num,questionnaire_num,level,svy_code,subcode_reason,multiplier
hhid,,,,,,,,,,,,,,,,,
46667201,1,12,6,13,1,2,2,110,3,NaN,2,1,H,1,1,NaN,16669
46667301,1,12,6,13,1,2,2,110,3,NaN,3,1,H,1,1,NaN,24840
46667302,1,12,6,13,1,2,2,110,3,NaN,3,2,H,1,1,NaN,24840
46667303,1,12,6,13,1,2,2,110,3,NaN,3,3,H,1,1,NaN,24840
46667304,1,12,6,13,1,2,2,110,3,NaN,3,4,H,1,1,NaN,24840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43277314,10,101,19,23,35,6,2,1011,16,NaN,3,14,H,1,1,NaN,157235
43277315,10,101,19,23,35,6,2,1011,16,NaN,3,15,H,1,1,NaN,157235
43277316,10,101,19,23,35,6,2,1011,16,NaN,3,16,H,1,1,NaN,157235
43277317,10,101,19,23,35,6,2,1011,16,NaN,3,17,H,1,1,NaN,157235
43277318,10,101,19,23,35,6,2,1011,16,NaN,3,18,H,1,1,NaN,157235

In [47]:
to_keep = ['sector', 'state', 'district', 'multiplier']
df[to_keep].to_parquet('04_clean/keycols.level_01.parquet')

In [48]:
xdf = pd.read_parquet('04_clean/keycols.level_01.parquet')
xdf

          sector  state  district  multiplier
hhid
46667201       1      1         6       16669
46667301       1      1         6       24840
46667302       1      1         6       24840
46667303       1      1         6       24840
46667304       1      1         6       24840
...          ...    ...       ...         ...
43277314       1     10        19      157235
43277315       1     10        19      157235
43277316       1     10        19      157235
43277317       1     10        19      157235
43277318       1     10        19      157235

[261953 rows x 4 columns]

---
## Level 2

In [51]:
df = pd.read_parquet('04_clean/level_02.parquet')
df.set_index(['hhid', 'person_id'], verify_integrity=True, inplace=True)
df.head()

                   questionnaire_num  level  rel_to_hoh  gender  age  \
hhid     person_id
22300101 3                         H      2           5       1   23
         2                         H      2           2       2   45
         4                         H      2           5       2   24
         1                         H      2           1       1   56
22300201 2                         H      2           2       2   44

                    marital_status  edu_level  edu_years  used_internet  \
hhid     person_id
22300101 3                       1         12       18.0            1.0
         2                       2          6       10.0            1.0
         4                       1         13       20.0            1.0
         1                       2         12       15.0            1.0
22300201 2                       2          5        8.0            2.0

                    days_outside_home  meals_daily  meals_school  \
hhid     person_id
22300101 3                        0.0          3.0           NaN
         2                        0.0          3.0           NaN
         4                        0.0          3.0           NaN
         1                        0.0          3.0           NaN
22300201 2                        0.0          3.0           NaN

                    meals_employer  meals_others  meals_payment  meals_home  \
hhid     person_id
22300101 3                     NaN           NaN            3.0        87.0
         2                     NaN           3.0            NaN        87.0
         4                     NaN           NaN            4.0        86.0
         1                     NaN           NaN            3.0        87.0
22300201 2                     NaN           NaN            NaN        90.0

                    member_status  original_member  multiplier
hhid     person_id
22300101 3                      1              1.0       57436
         2                      1              1.0       57436
         4                      1              1.0       57436
         1                      1              1.0       57436
22300201 2                      1              1.0       27497

In [82]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_02.parquet')

---
## Level 3

In [87]:
df = pd.read_parquet('04_clean/level_03.parquet')
df.set_index('hhid', verify_integrity=True, inplace=True)
df.head()

,questionnaire_num,level,hh_size,employed_annual,nco_2015,nic_2008,num_activities_income,hasincome_selfemp_agri,hasincome_wage_agri,hasincome_casual_agri,...,land_type,land_area,has_house,type_house,source_cooking,source_lighting,type_rationcard,is_rent,has_pmgky,multiplier
hhid,,,,,,,,,,,,,,,,,,,,,
22300101,H,3,4,1,112.0,47522.0,1.0,NaN,NaN,NaN,...,1.0,0.02,1,1.0,2,1,3,NaN,2,57436
22300201,H,3,4,1,112.0,73100.0,1.0,NaN,NaN,NaN,...,1.0,0.01,1,2.0,2,1,3,NaN,2,27497
22300202,H,3,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.01,1,1.0,2,1,3,NaN,2,27497
22300203,H,3,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.03,1,1.0,2,1,3,NaN,2,27497
22300204,H,3,2,1,231.0,85301.0,2.0,NaN,NaN,NaN,...,1.0,0.02,1,1.0,2,1,3,NaN,2,27497

In [96]:
df[df.columns[10:]]

,hh_type,hoh_religion,caste,has_land,land_type,land_area,has_house,type_house,source_cooking,source_lighting,type_rationcard,is_rent,has_pmgky,multiplier
hhid,,,,,,,,,,,,,,
22300101,1,1,3,1,1.0,0.02,1,1.0,2,1,3,NaN,2,57436
22300201,1,1,3,1,1.0,0.01,1,2.0,2,1,3,NaN,2,27497
22300202,9,1,3,1,1.0,0.01,1,1.0,2,1,3,NaN,2,27497
22300203,9,1,3,1,2.0,0.03,1,1.0,2,1,3,NaN,2,27497
22300204,2,3,3,1,1.0,0.02,1,1.0,2,1,3,NaN,2,27497
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49999314,5,2,9,1,2.0,0.33,1,1.0,1,1,4,2.0,1,79235
49999315,1,2,9,1,2.0,0.99,1,1.0,1,1,4,2.0,1,79235
49999316,6,2,9,1,2.0,0.66,1,1.0,1,1,4,2.0,1,79235
49999317,2,2,9,1,2.0,1.65,1,1.0,1,1,4,2.0,1,79235
49999318,2,2,9,1,2.0,0.99,1,1.0,1,1,0,2.0,2,79235

In [97]:
df['has_land'].value_counts(normalize=True)

has_land
1    0.931984
2    0.068016
Name: proportion, dtype: float64

In [99]:
has_land = df[df['has_land'] == 1]
has_land['land_type'].value_counts(normalize=True)

land_type
2.0    0.495883
1.0    0.490382
3.0    0.013734
Name: proportion, dtype: float64

In [104]:
df['type_house'].value_counts(normalize=True)

type_house
1.0    0.841010
2.0    0.140639
3.0    0.018351
Name: proportion, dtype: float64

In [105]:
df.head()

,questionnaire_num,level,hh_size,employed_annual,nco_2015,nic_2008,num_activities_income,hasincome_selfemp_agri,hasincome_wage_agri,hasincome_casual_agri,...,land_type,land_area,has_house,type_house,source_cooking,source_lighting,type_rationcard,is_rent,has_pmgky,multiplier
hhid,,,,,,,,,,,,,,,,,,,,,
22300101,H,3,4,1,112.0,47522.0,1.0,NaN,NaN,NaN,...,1.0,0.02,1,1.0,2,1,3,NaN,2,57436
22300201,H,3,4,1,112.0,73100.0,1.0,NaN,NaN,NaN,...,1.0,0.01,1,2.0,2,1,3,NaN,2,27497
22300202,H,3,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.01,1,1.0,2,1,3,NaN,2,27497
22300203,H,3,2,2,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.03,1,1.0,2,1,3,NaN,2,27497
22300204,H,3,2,1,231.0,85301.0,2.0,NaN,NaN,NaN,...,1.0,0.02,1,1.0,2,1,3,NaN,2,27497

In [106]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_03.parquet')

---
## Level 4

In [2]:
df = pd.read_parquet('04_clean/level_04.parquet')
df.set_index('hhid', verify_integrity=True, inplace=True)

In [5]:
df[df.columns[10:]]

,online_groceries,online_milkprod,online_veg,online_fruits,online_dryfruits,online_eggfishmeat,online_processed_served,online_processed_packed,online_other,performed_ceremony,meals_nonhh,multiplier
hhid,,,,,,,,,,,,
22300101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,5,57436
22300201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2,3,27497
22300202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,27497
22300203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3,27497
22300204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2,3,27497
...,...,...,...,...,...,...,...,...,...,...,...,...
49999314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,79235
49999315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,79235
49999316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,79235
49999317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,79235
49999318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,79235

In [7]:
(df[[c for c in df if c.startswith('online_')]].fillna(value=0).sum(axis=1) > 0).sum()

19842

In [10]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_04.parquet')

---

## Level 5

In [17]:
df = pd.read_parquet('04_clean/level_05.parquet')
df.set_index(['hhid', 'item_code'], verify_integrity=True, inplace=True)
df.head()

                   questionnaire_num  level  cons_home_qty  cons_home_value  \
hhid     item_code
22300101 129                       F      5            NaN              NaN
         253                       F      5            NaN              NaN
         279                       F      5            NaN              NaN
         202                       F      5            NaN              NaN
         112                       F      5            NaN              NaN

                    cons_total_qty  cons_total_value  source  multiplier
hhid     item_code
22300101 129                 27.60            1687.0     NaN       57436
         253                 50.00              40.0     1.0       57436
         279                   NaN             143.0     NaN       57436
         202                  1.50              75.0     1.0       57436
         112                  0.35              30.0     1.0       57436

In [18]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_05.parquet')

---
## Level 6

In [20]:
df = pd.read_parquet('04_clean/level_06.parquet')
df.set_index(['hhid', 'item_code'], verify_integrity=True, inplace=True)

In [21]:
df.head()

                   questionnaire_num  level  cons_total_qty  cons_total_value  \
hhid     item_code
22300101 13                        F      6             NaN               100
         292                       F      6            0.25                75
         299                       F      6             NaN               175
         289                       F      6             NaN               180
         280                       F      6            2.00               180

                    source  multiplier
hhid     item_code
22300101 13            1.0       57436
         292           1.0       57436
         299           NaN       57436
         289           NaN       57436
         280           NaN       57436

In [22]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_06.parquet')

---
## Level 7

In [29]:
df = pd.read_parquet('04_clean/level_07.parquet')
df.set_index('hhid', verify_integrity=True, inplace=True)
df.head()

,questionnaire_num,level,procured_kerosene_ration,received_subsidy_lpg,num_subsidized_lpg,received_free_electricity,is_hhmem_edu,num_hhmem_publicedu,num_hhmem_privedu,received_free_textbook,...,is_hospitalization,is_benefit_healthscheme,num_benefit_healthscheme,amt_benefit_healthscheme,online_fuel,online_toilet,online_edu,online_medicine,online_services,multiplier
hhid,,,,,,,,,,,,,,,,,,,,,
22300101,C,7,2,1,2.0,2,2,NaN,NaN,NaN,...,4,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,57436
22300201,C,7,2,1,2.0,2,2,NaN,NaN,NaN,...,4,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,27497
22300202,C,7,2,1,1.0,2,2,NaN,NaN,NaN,...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,27497
22300203,C,7,2,2,NaN,2,2,NaN,NaN,NaN,...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27497
22300204,C,7,2,1,1.0,2,2,NaN,NaN,NaN,...,4,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,27497

In [31]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_07.parquet')

---
## Level 8

In [32]:
df = pd.read_parquet('04_clean/level_08.parquet')
df.head()

,hhid,questionnaire_num,level,item_code,cons_home_qty,cons_home_value,cons_total_qty,cons_total_value,source,multiplier
0,22300101,C,8,346,NaN,NaN,0.2,40.0,1.0,57436
1,22300101,C,8,96,0.0,0.0,2.0,44.0,NaN,57436
2,22300101,C,8,332,NaN,NaN,320.0,2175.0,NaN,57436
3,22300101,C,8,336,NaN,NaN,2.0,4.0,1.0,57436
4,22300101,C,8,349,NaN,NaN,NaN,3079.0,NaN,57436

In [33]:
df['item_code'].unique()

array([346,  96, 332, 336, 349, 338, 342, 331, 334, 335, 341, 333, 345,
       340, 337, 344, 343])

In [34]:
df['item_code'].nunique()

17

In [35]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_08.parquet')

---
## Level 9

In [59]:
df = pd.read_parquet('04_clean/level_09.parquet')
df.set_index(['hhid', 'item_code'], inplace=True, verify_integrity=True)
df.head()

                   questionnaire_num  level  cons_total_value  multiplier
hhid     item_code
22300101 497                       C      9             100.0       57436
         540                       C      9              90.0       57436
         496                       C      9             500.0       57436
         453                       C      9             150.0       57436
         457                       C      9             150.0       57436

In [60]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_09.parquet')

---
## Level 10

In [62]:
df = pd.read_parquet('04_clean/level_10.parquet')
df.set_index(['hhid', 'item_code'], inplace=True, verify_integrity=True)
df.head()

                   questionnaire_num  level  cons_home_qty  cons_home_value  \
hhid     item_code
22300101 300                       C     10            NaN              NaN
         302                       C     10            NaN              NaN
         311                       C     10            NaN              NaN
         309                       C     10            NaN              NaN
         329                       C     10            NaN              NaN

                    cons_total_qty  cons_total_value  source  multiplier
hhid     item_code
22300101 300                  10.0                 5     1.0       57436
         302                  25.0                15     1.0       57436
         311                  20.0               240     1.0       57436
         309                   NaN                20     NaN       57436
         329                   NaN               700     NaN       57436

In [66]:
df.index.get_level_values(1).unique()

Index([300, 302, 311, 309, 329, 324, 319, 323, 301, 310, 322, 317, 312, 316,
       313, 315, 325, 314, 321, 320],
      dtype='int64', name='item_code')

In [67]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_10.parquet')

---
## Level 11

In [69]:
df = pd.read_parquet('04_clean/level_11.parquet')
df.set_index('hhid', verify_integrity=True, inplace=True)
df.head()

,questionnaire_num,level,online_clothing,online_footwear,online_furniture,online_mobile,online_personal_goods,online_rec,online_cooking,online_crockery,...,has_bicycle,has_bike,has_car,has_truck,has_animalcart,has_fridge,has_washingmachine,has_ac,type_tv,multiplier
hhid,,,,,,,,,,,,,,,,,,,,,
22300101,D,11,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,2.0,57436
22300201,D,11,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,27497
22300202,D,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,2.0,27497
22300203,D,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,2.0,27497
22300204,D,11,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,2.0,27497

In [70]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_11.parquet')

---
## Level 12

In [72]:
df = pd.read_parquet('04_clean/level_12.parquet')
df.set_index(['hhid', 'item_code'], verify_integrity=True, inplace=True)
df.head()

                   questionnaire_num  level  cons_total_qty  cons_total_value  \
hhid     item_code
22300101 367                       D     12             3.0            1200.0
         390                       D     12             1.0            2200.0
         379                       D     12             NaN           10285.0
         31                        D     12             6.0             900.0
         368                       D     12             NaN            1200.0

                    multiplier
hhid     item_code
22300101 367             57436
         390             57436
         379             57436
         31              57436
         368             57436

In [84]:
389 in df.index.get_level_values(1).unique()

True

In [75]:
df.index.get_level_values(1).nunique()

45

In [85]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_12.parquet')

---
## Level 13

In [87]:
df = pd.read_parquet('04_clean/level_13.parquet')
df.set_index(['hhid', 'item_code'], verify_integrity=True, inplace=True)
df.head()

                   questionnaire_num  level  num_firsthand_purchase  \
hhid     item_code
22300101 48                        D     13                     NaN
         557                       D     13                     NaN
         588                       D     13                     NaN
         603                       D     13                     1.0
         559                       D     13                     NaN

                    is_purchased_onhire  val_firsthand_purchase  repair_cost  \
hhid     item_code
22300101 48                         NaN                     NaN        300.0
         557                        2.0                   500.0          NaN
         588                        NaN                     NaN        750.0
         603                        2.0                  1200.0        100.0
         559                        NaN                  1000.0          NaN

                    num_secondhand_purchase  val_secondhand_purchase  \
hhid     item_code
22300101 48                             NaN                      NaN
         557                            NaN                      NaN
         588                            NaN                      NaN
         603                            NaN                      NaN
         559                            NaN                      NaN

                    tot_expenditure  multiplier
hhid     item_code
22300101 48                     300       57436
         557                    500       57436
         588                    750       57436
         603                   1300       57436
         559                   1000       57436

In [88]:
df.index.get_level_values(1).nunique()

78

In [108]:
649 in df.index.get_level_values(1).unique()

True

In [109]:
df.drop(['questionnaire_num', 'level'], axis=1).to_parquet('04_clean/keycols.level_13.parquet')

---
## Level 14

In [111]:
df = pd.read_parquet('04_clean/level_14.parquet')
df.set_index(['hhid', 'item_code'], inplace=True, verify_integrity=True)
df.head()

                   questionnaire_num  level  section  value  multiplier
hhid     item_code
22300101 309                       C     10     12.1     20       57436
         269                       F      5      6.7    261       57436
         249                       F      5      6.4    130       57436
         239                       F      5      6.3    345       57436
         459                       C      9      9.1   1310       57436

In [112]:
xdf = pd.read_parquet('04_clean/level_10.parquet').set_index(['hhid', 'item_code'], verify_integrity=True)
xdf.head()

                   questionnaire_num  level  cons_home_qty  cons_home_value  \
hhid     item_code
22300101 300                       C     10            NaN              NaN
         302                       C     10            NaN              NaN
         311                       C     10            NaN              NaN
         309                       C     10            NaN              NaN
         329                       C     10            NaN              NaN

                    cons_total_qty  cons_total_value  source  multiplier
hhid     item_code
22300101 300                  10.0                 5     1.0       57436
         302                  25.0                15     1.0       57436
         311                  20.0               240     1.0       57436
         309                   NaN                20     NaN       57436
         329                   NaN               700     NaN       57436

In [113]:
xdf.loc[(22300101, 309)]

questionnaire_num        C
level                   10
cons_home_qty          NaN
cons_home_value        NaN
cons_total_qty         NaN
cons_total_value        20
source                 NaN
multiplier           57436
Name: (22300101, 309), dtype: object

In [121]:
df.head()

                   questionnaire_num  level  section  value  multiplier
hhid     item_code
22300101 309                       C     10     12.1     20       57436
         269                       F      5      6.7    261       57436
         249                       F      5      6.4    130       57436
         239                       F      5      6.3    345       57436
         459                       C      9      9.1   1310       57436

In [146]:
dfs = {}
for level in df['level'].unique():
    dfs[level] = pd.read_parquet(f'04_clean/keycols.level_{level:02}.parquet')

dfs[8].set_index(['hhid', 'item_code'], inplace=True, verify_integrity=True)

In [149]:
from tqdm import tqdm

In [157]:
len(df)

8296569

In [161]:
cols_to_match = ['tot_expenditure', 'cons_total_value']

def check(ix, row):
    hhid, item_code = ix
    fdf = dfs[row.level]
    matching = [c for c in cols_to_match if c in fdf][0]
    old = fdf.loc[(hhid, item_code), matching]
    return (old == row.value) or pd.isna(old)

for ix, row in tqdm(df.sample(1000000).iterrows(), total=1000000):
    assert check(ix, row)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000000/1000000 [01:50<00:00, 9063.82it/s]

In [152]:
row

questionnaire_num        D
level                   12
section               13.1
value                35180
multiplier           78455
Name: (24750314, 379), dtype: object

In [154]:
dfs[12].loc[(24750314, 379)]

cons_total_qty          NaN
cons_total_value        NaN
multiplier          78455.0
Name: (24750314, 379), dtype: float64

In [162]:
df.to_parquet('04_clean/keycols.level_14.parquet')

---
## Level 15

In [163]:
df = pd.read_parquet('04_clean/level_15.parquet')
df.head()

,hhid,questionnaire_num,visit,level,section,time_taken,hh_usual_cons_exp_mnth,tot_online_exp,informant_code,response_code,hh_size,visit_month,multiplier
0,22300101,H,3,15,11.0,15,NaN,NaN,NaN,NaN,NaN,82024,57436
1,22300101,F,1,15,NaN,45,40000.0,2500.0,1.0,1.0,4.0,62024,57436
2,22300101,D,3,15,NaN,50,40000.0,7500.0,2.0,1.0,4.0,82024,57436
3,22300101,C,2,15,NaN,45,39000.0,2000.0,3.0,1.0,4.0,72024,57436
4,22300201,D,2,15,NaN,50,35000.0,7000.0,1.0,1.0,3.0,72024,27497

In [164]:
df.head(10)

,hhid,questionnaire_num,visit,level,section,time_taken,hh_usual_cons_exp_mnth,tot_online_exp,informant_code,response_code,hh_size,visit_month,multiplier
0,22300101,H,3,15,11.0,15,NaN,NaN,NaN,NaN,NaN,82024,57436
1,22300101,F,1,15,NaN,45,40000.0,2500.0,1.0,1.0,4.0,62024,57436
2,22300101,D,3,15,NaN,50,40000.0,7500.0,2.0,1.0,4.0,82024,57436
3,22300101,C,2,15,NaN,45,39000.0,2000.0,3.0,1.0,4.0,72024,57436
4,22300201,D,2,15,NaN,50,35000.0,7000.0,1.0,1.0,3.0,72024,27497
5,22300201,H,3,15,11.0,15,NaN,NaN,NaN,NaN,NaN,82024,27497
6,22300201,C,3,15,NaN,45,32000.0,4500.0,2.0,1.0,3.0,82024,27497
7,22300201,F,1,15,NaN,50,28000.0,500.0,3.0,1.0,4.0,62024,27497
8,22300202,C,1,15,NaN,45,17000.0,1500.0,1.0,1.0,2.0,62024,27497
9,22300202,F,2,15,NaN,40,17500.0,0.0,1.0,1.0,2.0,72024,27497

---
## Level 16

In [ ]:
mpce = pd.read_